### ISSUE TITLE
QueuedSinglePublisher shoud start publishing only after ResponseListenerPublisher subscribed

### ISSUE THREAD

**Issue by kptfh** [jetty-project/jetty-reactive-httpclient#10]
In concurrent environment faces the issue when QueuedSinglePublisher completed before ResponseListenerPublisher subscribed

**Comment by kptfh** [comment]
I mean that content publisher (QueuedSinglePublisher) should start emitting chunks only after ResponseListenerPublisher has emitted it's (response headers received) value . Otherwise semantic is not correct and such reactor construction will break if published on parallel scheduler 
[JettyReactiveHttpClient](https://github.com/kptfh/feign-reactive/blob/31552b20d071bf67fd2c1f4cbb2b6f1922e5b67e/feign-reactor-jetty/src/main/java/reactivefeign/jetty/client/JettyReactiveHttpClient.java#L129)

**Comment by sbordet** [comment]
I still don't understand.
`ResponseListenerPublisher` does not emit the "response headers received" event like you said.
The content publisher emits content chunks only after `ResponseListenerPublisher.onHeaders()` has returned.

Do you have a reproducible test case? Or otherwise can you explain _in detail_ what is it that does not work?

**Comment by kptfh** [comment]
Yeah. It's was not trivial to understand the root cause of an issue
To work reactively with Jetty reactive client it's convenient to have response in form of `Publisher<Pair<HEADERS, Publisher<CONTENT>>`
Thus for reactor I need to use following construction:
`Mono<MyReactiveHttpResponse> reactiveResponse = Mono.from(requestBuilder.build().response(
            (response, content) -> Mono.just(new MyReactiveHttpResponse(response.getResponse(), content))))`
Than usually use `reactiveResponse.flatMap(response -> response.getContent())`

Sometimes I face an issue that content publisher get completed before reactiveResponse published it's value
Will try to create short reproducible test but it may take some time

**Comment by kptfh** [comment]
I really like Jetty's reactive client implementation as it allows to start receiving reactive response before all reactive request body has been sent. But I'd like to have response in form of Publisher<JettyReactiveResponse<HEADERS, Publisher<CONTENT>>. It will greatly increase its usability.

**Comment by sbordet** [comment]
@kptfh would it be possible to see your implementation to understand the differences?

**Comment by kptfh** [comment]
sure, [jetty based reactive feign](https://github.com/Playtika/feign-reactive/blob/feature/tests_coverage/feign-reactor-jetty/src/main/java/reactivefeign/jetty/client/JettyReactiveResponseListener.java)

**Comment by sbordet** [comment]
@kptfh I don't see any difference - I think you can do the same without implementing your own `Response.Listener`.

```java
Mono<Pair<ReactiveResponse, Publisher<ContentChunk>>> = Mono.from(request.response((response, content) -> Mono.just(new Pair<>(response, content))));
```

That above is the `Publisher<Pair<HEADERS, Publisher<CONTENT>>` you are looking for.

**Comment by kptfh** [comment]
Regarding `Mono<Pair<ReactiveResponse, Publisher<ContentChunk>>> reactiveResponse = Mono.from(request.response((response, content) -> Mono.just(new Pair<>(response, content))));`

This approach works until you call `reactiveResponse.subscribeOn(Schedulers.parallel()).flatMap()`. In this case I face an issue that content publisher get completed before reactiveResponse published it's value.
Will create branch with broken tests so you can run/debug it locally

**Comment by kptfh** [comment]
[branch to reproduce failing tests](https://github.com/Playtika/feign-reactive/tree/feature/broken_jetty)

You should pay attention to this test [RetryingTest](https://github.com/Playtika/feign-reactive/blob/feature/broken_jetty/feign-reactor-jetty/src/test/java/reactivefeign/jetty/RetryingTest.java)

**Comment by sbordet** [comment]
@kptfh I found the cause of the issue and your branch is now passing the tests fine for me, thanks for that.

The problem was that in `ResponseListenerPublisher.onComplete()` there was this code:

```java
    public void onComplete(Result result) {
        if (result.isSucceeded()) {
            if (!content.complete()) {
                onComplete();
            }
        }
    }
```

The code was notifying `content` that the response content was completed, but then also calling `onComplete()` in case `content.complete()` returned `false`.
The call to `content.complete()` returns false if `content` has no subscribers.

In your case, you had no response content, and the subscription to `content` was performed asynchronously.
This may cause `ResponseListenerPublisher.onComplete()` and `content.complete()` to be called before the subscription to `content` is performed, and therefore `onComplete()` to be called.
This causes a race between the asynchronous thread that is performing the subscription (and call `request()` and therefore receive `onNext()` and `onComplete()` events) and the main thread that is handling response events.

**Comment by sbordet** [comment]
I released 1.0.2 with this fix.

**Comment by kptfh** [comment]
Great news. Thanks. Will update my code.

**Comment by kptfh** [comment]
@sbordet JFY Jetty based reactive feign client beats Netty based WebClient feign more then 40%
RealParallelRequestBenchmarks.jetty                  thrpt   15    114.371 ±  59.636  ops/s
RealParallelRequestBenchmarks.webClient         thrpt   15      81.120 ±  36.470  ops/s

https://github.com/Playtika/feign-reactive/blob/develop/feign-reactor-benchmarks/README.md

**Comment by sbordet** [comment]
Make Jetty the default then! :wink: 

Thanks for the feedback on performance!
