### ISSUE TITLE
Timeout issue

### ISSUE THREAD

**Issue by flyaruu** [jetty-project/jetty-reactive-httpclient#7]
The timeout and idle timeout don't terminate the stream.

If I take the RxJava2 example from the readme, and add timeouts and a doOnSuccess / doOnError listener like this:

```
	public static void main(String[] args) throws Exception {
		// Create and start Jetty's HttpClient.
		HttpClient httpClient = new HttpClient();
		httpClient.start();

		// Create a request using the HttpClient APIs.
		Request request = httpClient.newRequest("http://localhost:1234/path");
		request = request.idleTimeout(3000, TimeUnit.MILLISECONDS)
			.timeout(5000, TimeUnit.MILLISECONDS);
		
		// Wrap the request using the API provided by this project.
		ReactiveRequest reactiveRequest = ReactiveRequest.newBuilder(request).build();

		// Obtain a ReactiveStreams Publisher for the response, discarding the response content.
		Publisher<ReactiveResponse> publisher = reactiveRequest.response(ReactiveResponse.Content.discard());

		// Wrap the ReactiveStreams Publisher with RxJava.
		int status = Single.fromPublisher(publisher)
		        .map(ReactiveResponse::getStatus)
		        .doOnSuccess(s->System.err.println("Completed!"))
		        .doOnError(e->e.printStackTrace())
		        .blockingGet();				
		System.err.println("status: "+status);
	}
```
And I point it at a 'hanging socket':

Using 
```
nc -l 1234
```

... it will close the connection after the timeout, but it won't terminate the stream (neither doOnSuccess or doOnError gets called)

Granted, I could also add RxJava-level timeouts to the stream, but I still think this is a bug.

**Comment by gregw** [comment]
Versions of everything including the operating system?

Sorry, but due to vacations, you've only got me to look at this (and I'm on vacation too), and I'm not all that familiar with ReactiveStreams and less so with RxJava.... so just to check that such a timeout should be delivered to a RxJava subscriber via a call to onError?   If so, then the problem would be that we are not delivering that call? or could it be we are delivering the wrong exception type?   I assume there is a request(n>0) outstanding?  Is that required to deliver an error or can we call onError even if there is not request?  Answering my probably dumb questions will help us look at this before the end of our vacation period!

**Comment by flyaruu** [comment]
I'm using the master branch, MacOS 10.11.6, Java 1.8.0_141

I understand, enjoy your vacation, I think I got a handle on this.

I've done some digging around and actually the problem is a little bit more fundamental than I thought.

If I take the Rx2 example as-is, which points at http://localhost:8080/path, but I don't run anything on that port, I'd expect some kind of connection refused kind of error event, right?

I don't get that, it just hangs. Somehow the error events don't propagate at all.

**Comment by sbordet** [comment]
@flyaruu I fixed this in the latest code. Can you please verify that it works for you?

**Comment by flyaruu** [comment]
Looks great, cheers!
